# Generated by Django 5.0.6 on 2024-06-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
